server:
  port: 8081  # puerto web

lavalink:
  server:
    port: 2334          # puerto de audio
    bindAddress: 0.0.0.0
    password: "!68b826eb#ww1"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400